### ISSUE TITLE
I can't start TrafficToll because of a problem with modprobe

### ISSUE THREAD

**Issue by Santynu** [cryzed/TrafficToll#19]
I am trying to start TrafficToll on an Alpine docker image. When starting it gives me a modprobe error, it is trying to access a route that does not exist and I don't know if it should exist in Alpine.
I leave the complete trace of the execution.

/app/conf # tt eth@if255 example.yaml --logging-level DEBUG
2023-06-29 20:13:53.158 | INFO     | traffictoll.cli:main:109 - No global download rate specified, download traffic prioritization won't work
2023-06-29 20:13:53.158 | INFO     | traffictoll.cli:main:118 - No global upload rate specified, upload traffic prioritization won't work
2023-06-29 20:13:53.159 | INFO     | traffictoll.cli:main:154 - Setting up global class with unlimited download rate (minimum: 100kbps) and priority: 0
2023-06-29 20:13:53.159 | INFO     | traffictoll.cli:main:176 - Setting up global class with unlimited upload rate (minimum: 10kbps) and priority: 0
2023-06-29 20:13:53.159 | DEBUG    | traffictoll.utils:run:24 - tc qdisc add dev eth@if255 handle ffff: ingress
Cannot find device "eth@if255"
2023-06-29 20:13:53.164 | DEBUG    | traffictoll.utils:run:24 - modprobe ifb numifbs=1
**modprobe: FATAL: Module ifb not found in directory /lib/modules/5.15.0-72-generic**
2023-06-29 20:13:53.169 | ERROR    | traffictoll.__main__:main:25 - Unexpected error occurred:
Traceback (most recent call last):
  File "/usr/bin/tt", line 8, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7f4b150479d0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
> File "/usr/lib/python3.9/site-packages/traffictoll/__main__.py", line 17, in main
    cli_main(arguments)
    │        └ Namespace(device='eth@if255', config='a.yaml', delay=1, logging_level='DEBUG', speed_test=False)
    └ <function main at 0x7f4b142818b0>
  File "/usr/lib/python3.9/site-packages/traffictoll/cli.py", line 183, in main
    ingress_qdisc, egress_qdisc = tc_setup(
                                  └ <function tc_setup at 0x7f4b142814c0>
  File "/usr/lib/python3.9/site-packages/traffictoll/tc.py", line 138, in tc_setup
    ifb_device = _acquire_ifb_device()
                 └ <function _acquire_ifb_device at 0x7f4b14281280>
  File "/usr/lib/python3.9/site-packages/traffictoll/tc.py", line 68, in _acquire_ifb_device
    return _create_ifb_device()
           └ <function _create_ifb_device at 0x7f4b142811f0>
  File "/usr/lib/python3.9/site-packages/traffictoll/tc.py", line 48, in _create_ifb_device
    name = after.difference(before).pop()
           │     │          └ {'eth0', 'lo'}
           │     └ <method 'difference' of 'set' objects>
           └ {'eth0', 'lo'}

KeyError: 'pop from an empty set'
2023-06-29 20:13:53.181 | INFO     | traffictoll.tc:_clean_up:31 - Cleaning up IFB device
2023-06-29 20:13:53.182 | DEBUG    | traffictoll.utils:run:24 - rmmod ifb
rmmod: ERROR: Module ifb is not currently loaded

**Comment by sigmaSd** [comment]
Usually this happens when you update the kernel, and a reboot should fix this

**Comment by Santynu** [comment]
Thank you very much sigmaSd for your answer.
I rebuilt my docker image and the error changed to:
**modprobe: can't change directory to '/lib/modules': No such file or directory**
I have spent a couple of hours looking for this but I am not able to solve it.
Any ideas?

**Comment by sigmaSd** [comment]
Reading this issue https://gitlab.alpinelinux.org/alpine/aports/-/issues/10861

My takes is that since docker uses the host kernel, modprobe needs to look for kernel modules inside the host and not the docker image

but in that issue there is this bit
>, but using modprobe in a container doesn't make sense AFAIK since the container shares the kernel with the host.

So it seems like tt wont work in docker, because you need to load kernel modules in the host, and even if somehow this was supported I'm not sure how does that interact with tc inside the container

I guess this needs someone familiar with containers and unix to give a definite answer

**Comment by Santynu** [comment]
That is very strange and totally defeats the purpose of using docker...
I will try other alternatives, for my part, you can close the issue.
Thanks for your time!

**Comment by bmelanman** [comment]
Apologies for resurrecting a fairly dead thread on a fairly dead project, but I think I found a bit of a workaround for this issue that will make it (kinda) work in Docker! 

So it seems (and feel free to correct me if I'm wrong about something here) like the `modprobe` issue occurs because it first attempts to make a new `ifb` interface before it starts setting everything else up. In my case at least, I was able to circumvent this issue by simply doing it myself!

```
#!/bin/bash

# Create an ifb interface for TrafficToll if it doesn't exist
if [[ $(ip link show | grep -c ifb) -lt 1 ]]; then

    # Create an ifb interface
    ip link add ifb0 type ifb

    # Set the ifb interface up
    ip link set dev ifb0 up
fi
```

Upsides:
- Simple fix
- Easy to implement
- Allows `tt` to apply global limits

Downsides:
- Process-specific limits still don't work! :(

Unfortunately, applying limits to specific processes results in permissions errors:

```
(venv) root@container $ tt eth0 config/traffic-toll/config.yml --logging-level DEBUG
2023-09-14 11:46:32.270 | INFO     | traffictoll.cli:main:146 - Setting up global class with max download rate: 500kbps (minimum: 100kbps) and priority: 0
2023-09-14 11:46:32.270 | INFO     | traffictoll.cli:main:168 - Setting up global class with max upload rate: 100kbps (minimum: 10kbps) and priority: 0
2023-09-14 11:46:32.271 | DEBUG    | traffictoll.utils:run:24 - tc qdisc add dev eth0 handle ffff: ingress
2023-09-14 11:46:32.273 | DEBUG    | traffictoll.utils:run:24 - tc filter add dev eth0 parent ffff: protocol ip u32 match u32 0 0 action mirred egress redirect dev ifb0
2023-09-14 11:46:32.274 | DEBUG    | traffictoll.utils:run:24 - tc qdisc show dev ifb0
2023-09-14 11:46:32.276 | DEBUG    | traffictoll.utils:run:24 - tc qdisc add dev ifb0 root handle 1: htb
2023-09-14 11:46:32.277 | DEBUG    | traffictoll.utils:run:24 - tc class show dev ifb0
2023-09-14 11:46:32.279 | DEBUG    | traffictoll.utils:run:24 - tc class add dev ifb0 parent 1: classid 1:1 htb rate 500kbps
2023-09-14 11:46:32.280 | DEBUG    | traffictoll.utils:run:24 - tc class show dev ifb0
2023-09-14 11:46:32.281 | DEBUG    | traffictoll.utils:run:24 - tc class add dev ifb0 parent 1:1 classid 1:2 htb rate 100kbps ceil 500kbps prio 0
2023-09-14 11:46:32.283 | DEBUG    | traffictoll.utils:run:24 - tc filter add dev ifb0 parent 1: prio 2 protocol ip u32 match u32 0 0 flowid 1:2
2023-09-14 11:46:32.284 | DEBUG    | traffictoll.utils:run:24 - tc qdisc show dev eth0
2023-09-14 11:46:32.286 | DEBUG    | traffictoll.tc:_get_free_qdisc_id:98 - Failed to parse QDisc ID as base 10 integer on line: 'qdisc ingress ffff: parent ffff:fff1 ---------------- '
2023-09-14 11:46:32.286 | DEBUG    | traffictoll.utils:run:24 - tc qdisc add dev eth0 root handle 1: htb
2023-09-14 11:46:32.288 | DEBUG    | traffictoll.utils:run:24 - tc class show dev eth0
2023-09-14 11:46:32.289 | DEBUG    | traffictoll.utils:run:24 - tc class add dev eth0 parent 1: classid 1:1 htb rate 100kbps
2023-09-14 11:46:32.290 | DEBUG    | traffictoll.utils:run:24 - tc class show dev eth0
2023-09-14 11:46:32.292 | DEBUG    | traffictoll.utils:run:24 - tc class add dev eth0 parent 1:1 classid 1:2 htb rate 10kbps ceil 100kbps prio 0
2023-09-14 11:46:32.293 | DEBUG    | traffictoll.utils:run:24 - tc filter add dev eth0 parent 1: prio 2 protocol ip u32 match u32 0 0 flowid 1:2
2023-09-14 11:46:32.294 | INFO     | traffictoll.cli:main:251 - Setting up class for: 'Chromium' with max download rate: 500kbps (minimum: 10kbps) and priority: 0
2023-09-14 11:46:32.295 | DEBUG    | traffictoll.utils:run:24 - tc class show dev ifb0
2023-09-14 11:46:32.296 | DEBUG    | traffictoll.utils:run:24 - tc class add dev ifb0 parent 1:1 classid 1:3 htb rate 10kbps ceil 500kbps prio 0
2023-09-14 11:46:32.298 | INFO     | traffictoll.cli:main:277 - Setting up class for: 'Chromium' with max upload rate: 100kbps (minimum: 1kbps) and priority: 0
2023-09-14 11:46:32.298 | DEBUG    | traffictoll.utils:run:24 - tc class show dev eth0
2023-09-14 11:46:32.299 | DEBUG    | traffictoll.utils:run:24 - tc class add dev eth0 parent 1:1 classid 1:3 htb rate 1kbps ceil 100kbps prio 0
2023-09-14 11:46:32.304 | ERROR    | traffictoll.__main__:main:25 - Unexpected error occurred:
Traceback (most recent call last):
  File "/config/venv/bin/tt", line 8, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7f227363c9a0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
> File "/config/venv/lib/python3.11/site-packages/traffictoll/__main__.py", line 17, in main
    cli_main(arguments)
    │        └ Namespace(device='eth0', config='config/traffic-toll/config.yml', delay=1, logging_level='DEBUG', speed_test=False)
    └ <function main at 0x7f2272427740>
  File "/config/venv/lib/python3.11/site-packages/traffictoll/cli.py", line 332, in main
    filtered_connections = filter_net_connections(process_filter_predicates)
                           │                      └ [ProcessFilterPredicate(name='Chromium', conditions=[('exe', '/usr/lib/chromium/chromium')], recursive=False)]
                           └ <function filter_net_connections at 0x7f2272c32520>
  File "/config/venv/lib/python3.11/site-packages/traffictoll/net.py", line 49, in filter_net_connections
    if not _match_process(process, predicate):
           │              │        └ ProcessFilterPredicate(name='Chromium', conditions=[('exe', '/usr/lib/chromium/chromium')], recursive=False)
           │              └ psutil.Process(pid=1, name='s6-svscan', status='sleeping', started='20:25:17')
           └ <function _match_process at 0x7f2272425da0>
  File "/config/venv/lib/python3.11/site-packages/traffictoll/net.py", line 32, in _match_process
    if isinstance(value, int):

UnboundLocalError: cannot access local variable 'value' where it is not associated with a value
2023-09-14 11:46:32.308 | INFO     | traffictoll.cli:_clean_up:72 - Cleaning up QDiscs
2023-09-14 11:46:32.309 | DEBUG    | traffictoll.utils:run:24 - tc qdisc del dev ifb0 parent root
2023-09-14 11:46:32.310 | DEBUG    | traffictoll.utils:run:24 - tc qdisc del dev eth0 parent root
2023-09-14 11:46:32.312 | DEBUG    | traffictoll.utils:run:24 - tc qdisc del dev eth0 parent ffff:fff1
```

I tried to patch the issue further like so:

```
def _match_process(process: psutil.Process, predicate: ProcessFilterPredicate) -> bool:
    for condition in predicate.conditions:
        name, regex = condition

        <!-- PATCH START -->
        try:
            value = getattr(process, name)()
        except psutil.AccessDenied:
            logger.debug(
                "Access denied to attribute {} of process with PID {}",
                name,
                process.pid,
            )
            return False
        <!-- PATCH STOP -->

        if isinstance(value, int):
            value = str(value)
        elif isinstance(value, (list, tuple)):
            value = shlex.join(value)

        if not re.match(regex, value):
            return False

    return True
```
 However it seems to have only moved the metaphorical "Permissions Goal Posts" further down the field:
```
(venv) root@container $ tt eth0 config/traffic-toll/config.yml --logging-level DEBUG
2023-09-14 11:44:25.733 | INFO     | traffictoll.cli:main:146 - Setting up global class with max download rate: 500kbps (minimum: 100kbps) and priority: 0
2023-09-14 11:44:25.733 | INFO     | traffictoll.cli:main:168 - Setting up global class with max upload rate: 100kbps (minimum: 10kbps) and priority: 0
2023-09-14 11:44:25.733 | DEBUG    | traffictoll.utils:run:24 - tc qdisc add dev eth0 handle ffff: ingress
2023-09-14 11:44:25.735 | DEBUG    | traffictoll.utils:run:24 - tc filter add dev eth0 parent ffff: protocol ip u32 match u32 0 0 action mirred egress redirect dev ifb0
2023-09-14 11:44:25.737 | DEBUG    | traffictoll.utils:run:24 - tc qdisc show dev ifb0
2023-09-14 11:44:25.738 | DEBUG    | traffictoll.utils:run:24 - tc qdisc add dev ifb0 root handle 1: htb
2023-09-14 11:44:25.740 | DEBUG    | traffictoll.utils:run:24 - tc class show dev ifb0
2023-09-14 11:44:25.741 | DEBUG    | traffictoll.utils:run:24 - tc class add dev ifb0 parent 1: classid 1:1 htb rate 500kbps
2023-09-14 11:44:25.743 | DEBUG    | traffictoll.utils:run:24 - tc class show dev ifb0
2023-09-14 11:44:25.744 | DEBUG    | traffictoll.utils:run:24 - tc class add dev ifb0 parent 1:1 classid 1:2 htb rate 100kbps ceil 500kbps prio 0
2023-09-14 11:44:25.746 | DEBUG    | traffictoll.utils:run:24 - tc filter add dev ifb0 parent 1: prio 2 protocol ip u32 match u32 0 0 flowid 1:2
2023-09-14 11:44:25.747 | DEBUG    | traffictoll.utils:run:24 - tc qdisc show dev eth0
2023-09-14 11:44:25.749 | DEBUG    | traffictoll.tc:_get_free_qdisc_id:98 - Failed to parse QDisc ID as base 10 integer on line: 'qdisc ingress ffff: parent ffff:fff1 ---------------- '
2023-09-14 11:44:25.749 | DEBUG    | traffictoll.utils:run:24 - tc qdisc add dev eth0 root handle 1: htb
2023-09-14 11:44:25.751 | DEBUG    | traffictoll.utils:run:24 - tc class show dev eth0
2023-09-14 11:44:25.752 | DEBUG    | traffictoll.utils:run:24 - tc class add dev eth0 parent 1: classid 1:1 htb rate 100kbps
2023-09-14 11:44:25.753 | DEBUG    | traffictoll.utils:run:24 - tc class show dev eth0
2023-09-14 11:44:25.755 | DEBUG    | traffictoll.utils:run:24 - tc class add dev eth0 parent 1:1 classid 1:2 htb rate 10kbps ceil 100kbps prio 0
2023-09-14 11:44:25.756 | DEBUG    | traffictoll.utils:run:24 - tc filter add dev eth0 parent 1: prio 2 protocol ip u32 match u32 0 0 flowid 1:2
2023-09-14 11:44:25.758 | INFO     | traffictoll.cli:main:251 - Setting up class for: 'Chromium' with max download rate: 500kbps (minimum: 10kbps) and priority: 0
2023-09-14 11:44:25.758 | DEBUG    | traffictoll.utils:run:24 - tc class show dev ifb0
2023-09-14 11:44:25.759 | DEBUG    | traffictoll.utils:run:24 - tc class add dev ifb0 parent 1:1 classid 1:3 htb rate 10kbps ceil 500kbps prio 0
2023-09-14 11:44:25.760 | INFO     | traffictoll.cli:main:277 - Setting up class for: 'Chromium' with max upload rate: 100kbps (minimum: 1kbps) and priority: 0
2023-09-14 11:44:25.761 | DEBUG    | traffictoll.utils:run:24 - tc class show dev eth0
2023-09-14 11:44:25.762 | DEBUG    | traffictoll.utils:run:24 - tc class add dev eth0 parent 1:1 classid 1:3 htb rate 1kbps ceil 100kbps prio 0
2023-09-14 11:44:25.767 | DEBUG    | traffictoll.net:_match_process:25 - Access denied to attribute exe of process with PID 255
2023-09-14 11:44:25.768 | DEBUG    | traffictoll.net:_match_process:25 - Access denied to attribute exe of process with PID 256
2023-09-14 11:44:25.768 | DEBUG    | traffictoll.net:_match_process:25 - Access denied to attribute exe of process with PID 257
2023-09-14 11:44:25.768 | DEBUG    | traffictoll.net:_match_process:25 - Access denied to attribute exe of process with PID 258
2023-09-14 11:44:25.769 | DEBUG    | traffictoll.net:_match_process:25 - Access denied to attribute exe of process with PID 289
2023-09-14 11:44:25.769 | DEBUG    | traffictoll.net:_match_process:25 - Access denied to attribute exe of process with PID 1352
2023-09-14 11:44:25.769 | ERROR    | traffictoll.__main__:main:25 - Unexpected error occurred:
Traceback (most recent call last):
  File "/config/venv/lib/python3.11/site-packages/psutil/_pslinux.py", line 1653, in wrapper
    return fun(self, *args, **kwargs)
           │   │      │       └ {}
           │   │      └ ('inet',)
           │   └ <psutil._pslinux.Process object at 0x7f5700860cc0>
           └ <function Process.connections at 0x7f5700841440>
  File "/config/venv/lib/python3.11/site-packages/psutil/_pslinux.py", line 2243, in connections
    ret = _connections.retrieve(kind, self.pid)
          │            │        │     │    └ <member 'pid' of 'Process' objects>
          │            │        │     └ <psutil._pslinux.Process object at 0x7f5700860cc0>
          │            │        └ 'inet'
          │            └ <function Connections.retrieve at 0x7f5700839940>
          └ <psutil._pslinux.Connections object at 0x7f5700834c50>
  File "/config/venv/lib/python3.11/site-packages/psutil/_pslinux.py", line 989, in retrieve
    inodes = self.get_proc_inodes(pid)
             │    │               └ 1629
             │    └ <function Connections.get_proc_inodes at 0x7f5700839620>
             └ <psutil._pslinux.Connections object at 0x7f5700834c50>
  File "/config/venv/lib/python3.11/site-packages/psutil/_pslinux.py", line 816, in get_proc_inodes
    inode = readlink("%s/%s/fd/%s" % (self._procfs_path, pid, fd))
            │                         │    │             │    └ '0'
            │                         │    │             └ 1629
            │                         │    └ '/proc'
            │                         └ <psutil._pslinux.Connections object at 0x7f5700834c50>
            └ <function readlink at 0x7f5700838540>
  File "/config/venv/lib/python3.11/site-packages/psutil/_pslinux.py", line 210, in readlink
    path = os.readlink(path)
           │  │        └ '/proc/1629/fd/0'
           │  └ <built-in function readlink>
           └ <module 'os' (frozen)>

PermissionError: [Errno 13] Permission denied: '/proc/1629/fd/0'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/config/venv/bin/tt", line 8, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7f5701a249a0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
> File "/config/venv/lib/python3.11/site-packages/traffictoll/__main__.py", line 17, in main
    cli_main(arguments)
    │        └ Namespace(device='eth0', config='config/traffic-toll/config.yml', delay=1, logging_level='DEBUG', speed_test=False)
    └ <function main at 0x7f570081b740>
  File "/config/venv/lib/python3.11/site-packages/traffictoll/cli.py", line 332, in main
    filtered_connections = filter_net_connections(process_filter_predicates)
                           │                      └ [ProcessFilterPredicate(name='Chromium', conditions=[('exe', '/usr/lib/chromium/chromium')], recursive=False)]
                           └ <function filter_net_connections at 0x7f5700d8e520>
  File "/config/venv/lib/python3.11/site-packages/traffictoll/net.py", line 53, in filter_net_connections
    connections.update(process.connections())
    │           │      │       └ <function Process.connections at 0x7f5700843e20>
    │           │      └ psutil.Process(pid=1629, name='chromium', status='sleeping', started='10:19:25')
    │           └ <method 'update' of 'set' objects>
    └ set()
  File "/config/venv/lib/python3.11/site-packages/psutil/__init__.py", line 1171, in connections
    return self._proc.connections(kind)
           │    │     │           └ 'inet'
           │    │     └ <function Process.connections at 0x7f57008414e0>
           │    └ <psutil._pslinux.Process object at 0x7f5700860cc0>
           └ psutil.Process(pid=1629, name='chromium', status='sleeping', started='10:19:25')
  File "/config/venv/lib/python3.11/site-packages/psutil/_pslinux.py", line 1655, in wrapper
    raise AccessDenied(self.pid, self._name)
          │            │    │    │    └ <member '_name' of 'Process' objects>
          │            │    │    └ <psutil._pslinux.Process object at 0x7f5700860cc0>
          │            │    └ <member 'pid' of 'Process' objects>
          │            └ <psutil._pslinux.Process object at 0x7f5700860cc0>
          └ <class 'psutil.AccessDenied'>

psutil.AccessDenied: (pid=1629)
2023-09-14 11:44:25.777 | INFO     | traffictoll.cli:_clean_up:72 - Cleaning up QDiscs
2023-09-14 11:44:25.778 | DEBUG    | traffictoll.utils:run:24 - tc qdisc del dev ifb0 parent root
2023-09-14 11:44:25.779 | DEBUG    | traffictoll.utils:run:24 - tc qdisc del dev eth0 parent root
2023-09-14 11:44:25.781 | DEBUG    | traffictoll.utils:run:24 - tc qdisc del dev eth0 parent ffff:fff1
```

Feel free to discuss further either here or in a new thread, but this is will at least get things working good enough for the time being, and I'll see what I can do in the future (if anything lol). Thanks for reading!
