### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by IgubGit** [cryzed/TrafficToll#2]
When executing the command `tt ens160 config.yaml` as root I get the following error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/tt", line 11, in <module>
    load_entry_point('TrafficToll==0.1.0', 'console_scripts', 'tt')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/traffictoll/cli.py", line 85
    filter_id = tc_add_u32_filter(ingress_interface, f'match ip dport {port} 0xffff', ingress_qdisc_id, class_id)
                                                                                   ^
SyntaxError: invalid syntax
```

The operating system is "Ubuntu 18.04.2 LTS". The config file config.yaml contains the following:

```
# Global limits
download: 500kbps
upload: 100kbps
```

I also tried the full sample config from the Readme. Is this a misconfiguration or a bug?

**Comment by cryzed** [comment]
Neither a misconfiguration, nor a bug. The issue is that I'm using Python 3.6+ f-strings and you are apparently using a Python version older than that. Is updating your Python 3 version an option for you?

**Comment by IgubGit** [comment]
Python 3 was already installed (default on Ubuntu 18.04 LTS), but I mistakenly installed TrafficToll using `pip` (which refers to Python 2 by default). After using `pip3` instead (package `python3-pip`), everything works fine.

Thanks for your help and the great tool!

**Comment by cryzed** [comment]
That's great, glad to hear you are enjoying it!
