### ISSUE TITLE
Syntax error class_ids:

### ISSUE THREAD

**Issue by erlandn** [cryzed/TrafficToll#9]
Installed on Linux Mint
Example is from Readme.

~/Dokument/traffictoll $ tt example.yaml 
Traceback (most recent call last):
  File "/usr/local/bin/tt", line 7, in <module>
    from traffictoll.__main__ import main
  File "/usr/local/lib/python3.5/dist-packages/traffictoll/__main__.py", line 5, in <module>
    from .cli import get_argument_parser, main as cli_main
  File "/usr/local/lib/python3.5/dist-packages/traffictoll/cli.py", line 194
    class_ids: Dict[_TrafficType, Dict[str, int]] = {
             ^
SyntaxError: invalid syntax

**Comment by cryzed** [comment]
You'll need a more recent version of Python -- it's a joke that Linux Mint ships with 3.5 which was released 5 years ago, sorry.
